exports.types = {
  Matrix2D    : '2DMatrix',
  Matrix3D    : '3DMatrix',
  Indicator   : 'ActivityIndicator',
  AlertDialog : 'AlertDialog',
  Animation   : 'Animation',
  Button      : 'Button',
  ButtonBar   : 'ButtonBar',
  CoverFlow   : 'CoverFlow',
  DashItem    : 'DashboardItem',
  Dash        : 'DashboardView',
  EmailDialog : 'EmailDialog',
  Image       : 'ImageView',
  OptionDialog: 'OptionDialog',
  Label       : 'Label',
  Picker      : 'Picker',
  PickerRow   : 'PickerRow',
  PickerCol   : 'PickerColumn',
  ProgressBar : 'ProgressBar',
  Scroll      : 'ScrollView',
  Scrollable  : 'ScrollableView',
  SearchBar   : 'SearchBar',
  Slider      : 'Slider',
  Switch      : 'Switch',
  Tab         : 'Tab', 
  TabGroup    : 'TabGroup',
  TabbedBar   : 'TabbedBar',
  Table       : 'TableView',
  TableRow    : 'TableViewRow',
  TableSection: 'TableViewSection',
  TextArea    : 'TextArea',
  TextField   : 'TextField',
  Toolbar     : 'Toolbar',
  View        : 'View',
  Web         : 'WebView',
  Window      : 'Window',
  List        : 'ListView',
  Section     : 'ListSection'
};

exports.constructors = {
  Object      : Object,
  Template    : Object,
  Item        : Object
};

